image: Visual Studio 2017
configuration: Debug
platform: Any CPU

#environment:
  #PATH: "%BOOST_LIBRARYDIR%;%PATH%"

before_build:
  - nuget restore

build_script:
  - msbuild
  
after_build:
test_script:


on_finish:
  - curl -s https://raw.githubusercontent.com/report-ci/scripts/master/upload.py > upload.py